MemberRegisterManagementWebsitePro/Models/ErrorViewModel.cs
namespace MemberRegisterManagementWebsitePro.Models {
    public class ErrorViewModel {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MemberRegisterManagementWebsitePro/Models/Member.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MemberRegisterManagementWebsitePro.Models {
    public class Member {

        [Key]
        public int MemberId { get; set; }

        [Column(TypeName = "nvarchar(250)")]
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("First Name")]
        public string FirstName { get; set; }

        [Column(TypeName = "nvarchar(250)")]
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Last Name")]
        public string LastName { get; set; }

        [Column(TypeName = "varchar(100)")]
        public string Email { get; set; }

        [Column(TypeName = "varchar(100)")]
        public string PhoneNumber { get; set; }
    }
}

MemberRegisterManagementWebsitePro/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MemberRegisterManagementWebsitePro.Models;

namespace MemberRegisterManagementWebsitePro.Controllers {
    public class HomeController : Controller {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger) {
            _logger = logger;
        }

        public IActionResult Index() {
            return View();
        }

        public IActionResult Privacy() {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MemberRegisterManagementWebsitePro/Controllers/MemberController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MemberRegisterManagementWebsitePro.Models;
using MemberRegisterManagementWebsitePro.Data;
using Microsoft.EntityFrameworkCore;

namespace MemberRegisterManagementWebsitePro.Controllers {
    public class MemberController : Controller {
        private readonly MemberContext _context;

        public MemberController(MemberContext context) {
            _context = context;
        }

        public async Task<IActionResult> Index() {
            return View(await _context.Members.ToListAsync());
        }

        public async Task<IActionResult> Delete(int? id) {
            var member = await _context.Members.FindAsync(id);
            _context.Members.Remove(member);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Add() {
            return View(new Member());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([Bind("MemberId,FirstName,LastName,Email,PhoneNumber")] Member member) {
            if (ModelState.IsValid) {
                _context.Add(member);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(member);
        }

        public IActionResult Edit(int id) {
            return View(_context.Members.Find(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("MemberId,FirstName,LastName,Email,PhoneNumber,DateTimeBecameTheMember")] Member member) {
            if (ModelState.IsValid) {
                _context.Update(member);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(member);
        }
    }
}

MemberRegisterManagementWebsitePro/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">

    <h1 class="display-4">Membership Register Management System</h1>
   
</div>

MemberRegisterManagementWebsitePro/Views/Member/Add.cshtml
@model MemberRegisterManagementWebsitePro.Models.Member

@{
    ViewData["Title"] = "Create";
}

<h4>Member Form</h4>
<hr />
<div class="col-md-6">
    <form asp-action="Add">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="MemberId" />
        <div class="form-group">
            <label asp-for="FirstName" class="control-label"></label>
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="LastName" class="control-label"></label>
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <input type="submit" value="Submit"  class=" btn btn-success "/>
            </div>
            <div class="form-group col-md-6">
                <a asp-action="Index" class="btn btn-success btn-block"> Back to List</a>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MemberRegisterManagementWebsitePro/Views/Member/Edit.cshtml
@model MemberRegisterManagementWebsitePro.Models.Member

@{ ViewData["Title"] = "Edit"; }

<h4>Edit Form</h4>
<hr />
<div class="col-md-6">
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="MemberId" />
        <div class="form-group">
            <label asp-for="FirstName" class="control-label"></label>
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="LastName" class="control-label"></label>
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <input type="submit" value="Submit" class=" btn btn-success " />
            </div>
            <div class="form-group col-md-6">
                <a asp-action="Index" class="btn btn-success btn-block"> Back to List</a>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MemberRegisterManagementWebsitePro/Views/Member/Index.cshtml
@model IEnumerable<MemberRegisterManagementWebsitePro.Models.Member>

@{
    ViewData["Title"] = "Index";
}

<h4>Member Register</h4>

<table class="highlight">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                <a asp-action="Add" > Add New</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.MemberId">Edit</a>
                <a asp-action="Delete" asp-route-id="@item.MemberId" class="text-danger ml-1" onclick="return confirm('Are you sure to delete this record?')">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>

MemberRegisterManagementWebsitePro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MemberRegisterManagementWebsitePro</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://kit.fontawesome.com/77623b1dd4.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="light-red lighten-1" role="navigation">
            <div class="nav-wrapper container">
                <a id="logo-container" asp-controller="Home" asp-action="Index">Membership Management</a>
                <ul class="right hide-on-med-and-down">
                    <li><a asp-controller="Member" asp-action="Index">Member</a></li>
                    <li><a asp-controller="Home" asp-action="Privacy">Privacy</a></li>
                </ul>

                <ul id="nav-mobile" class="sidenav">
                    <li><a asp-controller="Member" asp-action="Index">Member</a></li>
                    <li><a asp-controller="Home" asp-action="Privacy">Privacy</a></li>
                </ul>
                <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MemberRegisterManagementWebsitePro - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>